export const projectTableData = [
  {
    id: 1,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Not Started",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 2,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "In Progress",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 3,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Completed",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 4,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Archived",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 5,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Not Started",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 6,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Not Started",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 7,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Not Started",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 8,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Not Started",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 9,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Not Started",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
  {
    id: 10,
    name: "Techyon Software",
    percentage: "50%",
    owner: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    status: "Not Started",
    startDate: "29/10/2024",
    endDate: "29/10/2025",
  },
];
