export const taskTableData = [
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Review",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "High",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "On Track",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "Medium",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "Delayed",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "Low",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Revision",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "None",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Review",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "High",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Review",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "High",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Review",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "High",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Review",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "High",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Review",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "High",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
  {
    id: "T1",
    name: "Task Number 1",
    team: "Not Associated",
    owner: "Techyon",
    status: "In Review",
    startDate: "00-00-2024",
    endDate: "00-00-2024",
    expStartDate: "00-00-2024",
    expEndDate: "00-00-2024",
    duration: "3 Days",
    priority: "High",
    createdBy: "Techyon",
    task: {
      total: 20,
      completed: 10,
    },
    subTask: {
      total: 20,
      completed: 10,
    },
    completionDate: "00-00-2024",
    workHours: "01:00",
    deferences: "1:00",
    billingType: "None",
    filesCount: "1",
    lastEditedDate: "00-00-2024",
    requirementType: "BRD",
    requirementId: "R1",
    associatedMembers: "#SPOC1, #SPOC2",
    impactedDepartment: "Finance",
    suntaskLastUpdated: "Finance",
    reviewerDetails: "Finance",
  },
];
